version: '3.7'

networks:
  ph-test:
   external: true

services:
  extract-facebook:
    container_name: ph_extract_facebook
    build: .
    command: >
      sh -c "python -u ./main.py"
    env_file:
      - .env
    depends_on:
      - selenium
    volumes:
      - .:/app
    networks:
      - ph-test

  selenium:
    container_name: ph_selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=6
    shm_size: '2gb'
    networks:
      - ph-test

